name: Automated deployment

on:
  push:
    branches: ["main"]

jobs:
  build_push_deploy:
    name: Build code
    runs-on: ubuntu-latest
    steps: 
      - name: checkout 
        uses: actions/checkout@v3

      - name: Docker meta tag
        id: meta
        uses: docker/metadata-action@v4
        with:
            images: vaishnaviwohlig/first
            tags: |
              type=raw,value={{date 'YYYYMMDDhhmmss'}}

      - name: Login to docker
        run: |
              echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      
      - name: Push to hub
        uses: docker/build-push-action@v4
        with: 
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  
